### ISSUE TITLE
It looks like this plugin has a problem

### ISSUE THREAD

**Issue by PUDGE133** [iopietro/BetterScp939#3]
After SCP-939 dies, the player who was SCP-939's object is given a small model size while spawning. I believe that the effects of sight sometimes break down and persist in a non-SCP object.

**Comment by iopietro** [comment]
Yeah, I'm working on a fix, it apparently broke with the last one or two update.

**Comment by PUDGE133** [comment]
> Yeah, I'm working on a fix, it apparently broke with the last one or two update.

1.0.7 solved this problem?

**Comment by iopietro** [comment]
Yep.
